/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iamSoftware.Interfaces;


import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author ga_br
 */
public class PDVCaixa extends javax.swing.JFrame {
    
   
    /**
     * Creates new form PDVCaixa
     */
    public PDVCaixa() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton1.setText("Mapa de Caixa");
        getContentPane().add(jButton1);
        jButton1.setBounds(214, 28, 103, 23);

        jButton2.setText("Sangria");
        getContentPane().add(jButton2);
        jButton2.setBounds(323, 28, 103, 23);

        jButton3.setText("Suprimento");
        getContentPane().add(jButton3);
        jButton3.setBounds(432, 28, 103, 23);

        jLabel1.setText("Produto:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(201, 96, 42, 14);

        mainTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainTextFieldActionPerformed(evt);
            }
        });
        mainTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mainTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mainTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(mainTextField);
        mainTextField.setBounds(250, 90, 255, 20);

        jLabel2.setText("Quant.:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(512, 96, 38, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(554, 93, 40, 20);

        jButton4.setText("Inserir");
        getContentPane().add(jButton4);
        jButton4.setBounds(604, 92, 63, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Cód.", "Produto", "Quant.", "Valor Unit.", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(7);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(7);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(13);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(13);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(201, 133, 617, 263);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão", "À Prazo", "Cheque", "Convenio" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(317, 519, 135, 20);

        jLabel3.setText("Método de Pagamento:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(201, 522, 112, 14);

        jButton5.setText("Finalizar Venda");
        getContentPane().add(jButton5);
        jButton5.setBounds(613, 518, 105, 23);

        jButton6.setText("Cancelar Venda");
        getContentPane().add(jButton6);
        jButton6.setBounds(500, 518, 107, 23);

        jButton7.setText("Fechar Caixa");
        getContentPane().add(jButton7);
        jButton7.setBounds(724, 518, 95, 23);

        jLabel4.setText("Total R$:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(740, 477, 44, 14);

        jLabel5.setText("00,00");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(790, 477, 28, 14);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(250, 110, 255, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainTextFieldActionPerformed
        
    
    }//GEN-LAST:event_mainTextFieldActionPerformed

    private void mainTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainTextFieldKeyPressed
    }//GEN-LAST:event_mainTextFieldKeyPressed

    private void mainTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainTextFieldKeyReleased
   
    }//GEN-LAST:event_mainTextFieldKeyReleased

    private void mainTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainTextFieldKeyTyped
   
    }//GEN-LAST:event_mainTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PDVCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PDVCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PDVCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PDVCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PDVCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField mainTextField;
    // End of variables declaration//GEN-END:variables
}
